#!/usr/bin/env python3
"""
Token ID Decoder for Rene Model Output

This script reads token IDs from a binary file (generated by the OpenCL C++ driver)
and decodes them back to text using the OLMo tokenizer (same as Rene model).
"""

import argparse
import struct
import sys
from pathlib import Path

try:
    from transformers import AutoTokenizer
    import os
except ImportError:
    print("Error: transformers library not found. Install with: pip install transformers")
    sys.exit(1)


def load_tokenizer(tokenizer_name: str = "allenai/OLMo-1B-hf", token: str = None):
    """Load the tokenizer."""
    print(f"Loading tokenizer: {tokenizer_name}")
    
    # Try to get token from environment or use provided token
    if token is None:
        token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")
    
    # Try local files first (faster, works if already downloaded)
    tokenizer = None
    try:
        tokenizer = AutoTokenizer.from_pretrained(
            tokenizer_name,
            token=token,
            local_files_only=True
        )
        print("✓ Loaded tokenizer from local cache")
    except Exception as e:
        # If local files don't work, try downloading (requires auth if gated)
        if "404" in str(e) or "not found" in str(e).lower():
            print("Tokenizer not in cache, attempting to download...")
            try:
                tokenizer = AutoTokenizer.from_pretrained(
                    tokenizer_name,
                    token=token,
                    local_files_only=False
                )
                print("✓ Loaded tokenizer")
            except Exception as e2:
                if "401" in str(e2) or "Unauthorized" in str(e2):
                    print("\nError: Authentication required to access this tokenizer.")
                    print("Please authenticate with Hugging Face:")
                    print("  1. Get a token from: https://huggingface.co/settings/tokens")
                    print("  2. Run: huggingface-cli login")
                    print("  3. Or set environment variable: export HF_TOKEN=your_token_here")
                    print("\nAlternatively, if you've already accepted the model terms on Hugging Face,")
                    print("make sure you're logged in via: huggingface-cli login")
                raise e2
        else:
            raise
    
    return tokenizer


def read_tokens_binary_simple(input_path: Path):
    """
    Read token IDs from binary file written by main_rene.cpp.
    Format: Just raw int32_t values (little-endian), no count header.
    """
    with open(input_path, 'rb') as f:
        data = f.read()
    
    # Each token is 4 bytes (int32_t)
    num_tokens = len(data) // 4
    if len(data) % 4 != 0:
        print(f"Warning: File size ({len(data)} bytes) is not a multiple of 4")
    
    tokens = []
    for i in range(num_tokens):
        token_id = struct.unpack('<i', data[i*4:(i+1)*4])[0]
        tokens.append(token_id)
    
    return tokens


def read_tokens_binary_with_count(input_path: Path):
    """
    Read token IDs from binary file written by dump_tokens.py.
    Format: int32_t count, followed by int32_t token IDs.
    """
    with open(input_path, 'rb') as f:
        # Read count
        count_data = f.read(4)
        if len(count_data) < 4:
            raise ValueError("File too short to contain count")
        count = struct.unpack('<i', count_data)[0]
        
        # Read tokens
        tokens = []
        for _ in range(count):
            token_data = f.read(4)
            if len(token_data) < 4:
                raise ValueError(f"File ended unexpectedly while reading tokens (expected {count}, got {len(tokens)})")
            token_id = struct.unpack('<i', token_data)[0]
            tokens.append(token_id)
    
    return tokens


def decode_tokens(tokens: list, tokenizer):
    """Decode token IDs to text."""
    # Decode the full sequence
    full_text = tokenizer.decode(tokens, skip_special_tokens=False)
    
    # Also decode individual tokens for debugging
    token_texts = []
    for token_id in tokens:
        token_text = tokenizer.decode([token_id], skip_special_tokens=False)
        token_texts.append(token_text)
    
    return full_text, token_texts


def main():
    parser = argparse.ArgumentParser(
        description="Decode token IDs from binary file back to text"
    )
    parser.add_argument(
        "input_file",
        type=Path,
        help="Input binary file with token IDs"
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        help="Output text file (default: print to stdout)"
    )
    parser.add_argument(
        "--tokenizer",
        type=str,
        default="allenai/OLMo-1B-hf",
        help="Tokenizer name (default: allenai/OLMo-1B-hf)"
    )
    parser.add_argument(
        "--token",
        type=str,
        default=None,
        help="Hugging Face token for authentication (or set HF_TOKEN env var)"
    )
    parser.add_argument(
        "--format",
        type=str,
        choices=["simple", "with_count", "auto"],
        default="auto",
        help="Input file format: 'simple' (just tokens), 'with_count' (count + tokens), 'auto' (detect)"
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Show individual token decodings"
    )
    
    args = parser.parse_args()
    
    if not args.input_file.exists():
        print(f"Error: Input file not found: {args.input_file}")
        sys.exit(1)
    
    # Detect format if auto
    if args.format == "auto":
        file_size = args.input_file.stat().st_size
        # Try with_count format first (read first 4 bytes as count)
        with open(args.input_file, 'rb') as f:
            count_data = f.read(4)
            if len(count_data) == 4:
                count = struct.unpack('<i', count_data)[0]
                # Heuristic: if count is reasonable and file size matches, use with_count format
                if 0 < count < 100000 and file_size == 4 + count * 4:
                    args.format = "with_count"
                else:
                    args.format = "simple"
            else:
                args.format = "simple"
    
    # Read tokens
    print(f"Reading tokens from: {args.input_file}")
    try:
        if args.format == "with_count":
            tokens = read_tokens_binary_with_count(args.input_file)
        else:
            tokens = read_tokens_binary_simple(args.input_file)
    except Exception as e:
        print(f"Error reading tokens: {e}")
        sys.exit(1)
    
    print(f"Read {len(tokens)} token IDs")
    if args.verbose:
        print(f"Token IDs: {tokens[:50]}{'...' if len(tokens) > 50 else ''}")
    
    # Load tokenizer
    tokenizer = load_tokenizer(args.tokenizer, token=args.token)
    
    # Decode tokens
    print("Decoding tokens...")
    full_text, token_texts = decode_tokens(tokens, tokenizer)
    
    # Output results
    output_lines = []
    output_lines.append("=" * 60)
    output_lines.append("Decoded Token Sequence")
    output_lines.append("=" * 60)
    output_lines.append(f"Token Count: {len(tokens)}")
    output_lines.append("")
    
    if args.verbose:
        output_lines.append("Individual Tokens:")
        output_lines.append("-" * 60)
        output_lines.append(f"{'Index':<8} {'Token ID':<12} {'Token Text':<40}")
        output_lines.append("-" * 60)
        for idx, (token_id, token_text) in enumerate(zip(tokens, token_texts)):
            # Clean up token text for display
            token_text_clean = repr(token_text) if any(ord(c) < 32 or c in ['\n', '\r', '\t'] for c in token_text) else token_text
            output_lines.append(f"{idx:<8} {token_id:<12} {token_text_clean}")
        output_lines.append("")
        output_lines.append("-" * 60)
        output_lines.append("")
    
    output_lines.append("Decoded Text:")
    output_lines.append("-" * 60)
    output_lines.append(full_text)
    output_lines.append("-" * 60)
    
    output_text = "\n".join(output_lines)
    
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(output_text)
        print(f"\n✓ Output written to: {args.output}")
    else:
        print("\n" + output_text)
    
    print("\nDone!")


if __name__ == "__main__":
    main()

