[build-system]
requires = [
  "setuptools>=42",
  "cmake>=3.24",
  "mlx==0.17.1",
  "nanobind==2.1.0",
  "transformers>=4.40.0",
  "datasets",
  "torch",
  "numpy<2",
  "requests",
  "huggingface_hub"
]
build-backend = "setuptools.build_meta"
